In [15]:

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import log_loss
from IPython.display import Image
import pandas as pd
import numpy as np
import pydotplus 
import os
import csv
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings, random
warnings.filterwarnings(action='ignore')

from sklearn.metrics import log_loss
from sklearn.model_selection import StratifiedKFold



In [16]:

train_data = pd.read_csv('/content/drive/MyDrive/new_data/new_train_scaled+kmeans.csv')
test_data = pd.read_csv('/content/drive/MyDrive/new_data/new_test_scaled+kmeans.csv')
train_data_label=pd.read_csv('/content/drive/MyDrive/new_data/new_train_label_scaled+kmeans.csv')
test_data_label=pd.read_csv('/content/drive/MyDrive/new_data/new_test_label_scaled+kmeans.csv')


In [17]:
train_data


gender  car  reality  income_total  income_type  edu_type  family_type  \
0         0.0  1.0      1.0      0.495528         0.00      0.00         0.00   
1         0.0  0.0      0.0      0.433722         0.25      0.25         0.00   
2         1.0  1.0      0.0      0.395811         0.25      0.00         0.00   
3         0.0  1.0      0.0      0.350973         0.25      0.00         0.00   
4         1.0  1.0      1.0      0.521439         0.25      0.00         0.00   
...       ...  ...      ...           ...          ...       ...          ...   
13223     0.0  0.0      0.0      0.521439         0.25      0.00         0.75   
13224     0.0  1.0      1.0      0.585963         0.50      0.25         0.00   
13225     0.0  0.0      1.0      0.395811         0.25      0.00         1.00   
13226     1.0  0.0      1.0      0.433722         0.50      0.00         0.00   
13227     0.0  1.0      1.0      0.225345         0.25      0.25         0.00   

       house_type  DAYS_BIRTH  DAYS_EMPLOYED  work_phone  email  occyp_type  \
0             0.0    0.649166       0.000000         0.0    0.0    0.000000   
1             0.0    0.462429       0.593706         0.0    0.0    0.055556   
2             0.0    0.331174       0.776724         1.0    0.0    0.111111   
3             0.0    0.261650       0.519263         0.0    0.0    0.166667   
4             0.0    0.485470       0.804310         0.0    0.0    0.222222   
...           ...         ...            ...         ...    ...         ...   
13223         0.0    0.742363       0.893915         0.0    0.0    0.444444   
13224         0.0    0.613515       0.844069         0.0    0.0    0.055556   
13225         0.0    0.396630       0.927880         0.0    1.0    0.000000   
13226         0.0    0.170287       0.802328         0.0    1.0    0.111111   
13227         0.0    0.241875       0.764974         0.0    0.0    0.000000   

       family_size  begin_month        ID   cluster  
0         0.071429     0.883333  0.000000  1.000000  
1         0.142857     0.433333  0.000154  0.777778  
2         0.071429     0.150000  0.000308  0.333333  
3         0.214286     0.200000  0.000463  0.555556  
4         0.142857     0.050000  0.000617  0.666667  
...            ...          ...       ...       ...  
13223     0.000000     0.716667  0.738514  0.777778  
13224     0.071429     0.883333  0.287080  0.555556  
13225     0.071429     0.566667  0.999846  0.111111  
13226     0.142857     0.266667  0.204903  0.888889  
13227     0.214286     0.066667  1.000000  0.555556  

[13228 rows x 17 columns]

In [18]:


X_train = np.array(pd.DataFrame(train_data, columns=[	'gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID', 'cluster'
]))
y_train = np.array(pd.DataFrame(train_data_label, columns=['credit']))



X_test =np.array( pd.DataFrame(test_data, columns=['gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID', 'cluster']))
y_test = np.array(pd.DataFrame(test_data_label, columns=['credit']))





In [19]:

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
from imblearn.metrics import specificity_score

import warnings
warnings.filterwarnings(action = 'ignore')



data = pd.DataFrame(X_train)
data['label'] = y_train



model = DecisionTreeClassifier(max_depth=35)


SPLITS = 10
skf = StratifiedKFold(n_splits = SPLITS)
n_iter = 0

features = data.iloc[:,:-1]
label = pd.DataFrame(data['label'])

score_list = []
rscore_list=[]

for train_idx, test_idx in skf.split(features, label):
  n_iter += 1
  print(f'--------------------{n_iter}번째 KFold-------------------')
  print(f'학습 값 : {len(train_idx)} / 검증값 : {len(test_idx)}')
  print('학습 레이블 데이터 분포: \n', train_idx)
  print('검증 레이블 데이터 분포: \n', test_idx)

  label_train = label.iloc[train_idx]
  label_test = label.iloc[test_idx]

  X_train_1, X_test_1 = features.iloc[train_idx, :], features.iloc[test_idx, :]
  y_train_1, y_test_1 = label.iloc[train_idx,:], label.iloc[test_idx,:]

  model.fit(X_train_1, y_train_1)
  preds = model.predict(X_test_1)
  score = f1_score(y_test_1, preds)
  rscore=specificity_score(y_test_1,preds)


  print(f'{n_iter}번째 단일 f1_score:{score}')
  
  print(f'{n_iter}번째 단일 specificity_score:{rscore}')


  score_list.append(score)
  rscore_list.append(rscore)

  

print('======================================================')
print(f'최종 평균 f1_score : {sum(score_list)/len(score_list)}')
print(f'최종 평균 specificity_score : {sum(rscore_list)/len(rscore_list)}')



--------------------1번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [ 1310  1311  1312 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [   0    1    2 ... 1420 1429 1440]
1번째 단일 f1_score:0.8881057268722466
1번째 단일 specificity_score:0.37888198757763975
--------------------2번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [1310 1311 1312 ... 2697 2698 2702]
2번째 단일 f1_score:0.8997407087294726
2번째 단일 specificity_score:0.3105590062111801
--------------------3번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [2636 2637 2638 ... 4038 4053 4064]
3번째 단일 f1_score:0.8821752265861027
3번째 단일 specificity_score:0.17391304347826086
--------------------4번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [3955 3957 3958 ... 5487 5497 5506]
4번째 단일 f1_sco