In [1]:

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import log_loss
from IPython.display import Image
import pandas as pd
import numpy as np
import pydotplus 
import os
import csv
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings, random
warnings.filterwarnings(action='ignore')

from sklearn.metrics import log_loss
from sklearn.model_selection import StratifiedKFold

In [2]:

train_data = pd.read_csv('/content/drive/MyDrive/new_data/new_train.csv')
test_data = pd.read_csv('/content/drive/MyDrive/new_data/new_test.csv')
train_data_label=pd.read_csv('/content/drive/MyDrive/new_data/new_train_label.csv')
test_data_label=pd.read_csv('/content/drive/MyDrive/new_data/new_test_label.csv')


In [3]:
train_data


gender  car  reality  income_total  income_type  edu_type  family_type  \
0           0    1        1     12.218495            1         1            1   
1           0    0        0     11.967181            2         2            1   
2           1    1        0     11.813030            2         1            1   
3           0    1        0     11.630709            2         1            1   
4           1    1        1     12.323856            2         1            1   
...       ...  ...      ...           ...          ...       ...          ...   
13223       0    0        0     12.323856            2         1            4   
13224       0    1        1     12.586220            3         2            1   
13225       0    0        1     11.813030            2         1            5   
13226       1    0        1     11.967181            3         1            1   
13227       0    1        1     11.119883            2         2            1   

       house_type  DAYS_BIRTH  DAYS_EMPLOYED  work_phone  email  occyp_type  \
0               1       19031       0.000000           0      0           1   
1               1       15773       5.736572           0      0           2   
2               1       13483       7.504942           1      0           3   
3               1       12270       5.017280           0      0           4   
4               1       16175       7.771489           0      0           5   
...           ...         ...            ...         ...    ...         ...   
13223           1       20657       8.637285           0      0           9   
13224           1       18409       8.155649           0      0           2   
13225           1       14625       8.965462           0      1           1   
13226           1       10676       7.752335           0      1           3   
13227           1       11925       7.391415           0      0           1   

       family_size  begin_month    ID  
0                2           53     1  
1                3           26     2  
2                2            9     3  
3                4           12     4  
4                3            3     5  
...            ...          ...   ...  
13223            1           43  4791  
13224            2           53  1863  
13225            2           34  6486  
13226            3           16  1330  
13227            4            4  6487  

[13228 rows x 16 columns]

In [4]:


X_train = np.array(pd.DataFrame(train_data, columns=[	'gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID'
]))
y_train = np.array(pd.DataFrame(train_data_label, columns=['credit']))



X_test =np.array( pd.DataFrame(test_data, columns=['gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID']))
y_test = np.array(pd.DataFrame(test_data_label, columns=['credit']))




In [5]:

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
from imblearn.metrics import specificity_score

import warnings
warnings.filterwarnings(action = 'ignore')



data = pd.DataFrame(X_train)
data['label'] = y_train



model = DecisionTreeClassifier(max_depth=35)


SPLITS = 10
skf = StratifiedKFold(n_splits = SPLITS)
n_iter = 0

features = data.iloc[:,:-1]
label = pd.DataFrame(data['label'])

score_list = []
rscore_list=[]

for train_idx, test_idx in skf.split(features, label):
  n_iter += 1
  print(f'--------------------{n_iter}번째 KFold-------------------')
  print(f'학습 값 : {len(train_idx)} / 검증값 : {len(test_idx)}')
  print('학습 레이블 데이터 분포: \n', train_idx)
  print('검증 레이블 데이터 분포: \n', test_idx)

  label_train = label.iloc[train_idx]
  label_test = label.iloc[test_idx]

  X_train_1, X_test_1 = features.iloc[train_idx, :], features.iloc[test_idx, :]
  y_train_1, y_test_1 = label.iloc[train_idx,:], label.iloc[test_idx,:]

  model.fit(X_train_1, y_train_1)
  preds = model.predict(X_test_1)
  score = f1_score(y_test_1, preds)
  rscore=specificity_score(y_test_1,preds)


  print(f'{n_iter}번째 단일 f1_score:{score}')
  
  print(f'{n_iter}번째 단일 specificity_score:{rscore}')


  score_list.append(score)
  rscore_list.append(rscore)

  

print('======================================================')
print(f'최종 평균 f1_score : {sum(score_list)/len(score_list)}')
print(f'최종 평균 specificity_score : {sum(rscore_list)/len(rscore_list)}')


--------------------1번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [ 1310  1311  1312 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [   0    1    2 ... 1420 1429 1440]
1번째 단일 f1_score:0.8910284463894966
1번째 단일 specificity_score:0.34782608695652173
--------------------2번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [1310 1311 1312 ... 2697 2698 2702]
2번째 단일 f1_score:0.8909169926119079
2번째 단일 specificity_score:0.2919254658385093
--------------------3번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [2636 2637 2638 ... 4038 4053 4064]
3번째 단일 f1_score:0.8846815834767642
3번째 단일 specificity_score:0.16770186335403728
--------------------4번째 KFold-------------------
학습 값 : 11905 / 검증값 : 1323
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [3955 3957 3958 ... 5487 5497 5506]
4번째 단일 f1_sco