In [8]:
import pandas as pd
import numpy as np
import pydotplus 
import os
from pprint import pprint
import csv
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, log_loss
from sklearn.model_selection import KFold


In [23]:
# 기본
test_data = pd.read_csv('new_test_scaled.csv')
test_data_label = pd.read_csv('new_test_label_scaled.csv')
train_data = pd.read_csv('new_train_scaled.csv')
train_data_label = pd.read_csv('new_train_label_scaled.csv')

In [28]:
# scaled + kmeans
test_data = pd.read_csv('new_test_scaled+kmeans.csv')
test_data_label = pd.read_csv('new_test_label_scaled+kmeans.csv')
train_data = pd.read_csv('new_train_scaled+kmeans.csv')
train_data_label = pd.read_csv('new_train_label_scaled+kmeans.csv')

In [173]:
# scaled + som
test_data = pd.read_csv('new_test_scaled+som.csv')
test_data_label = pd.read_csv('new_test_label_scaled+som.csv')
train_data = pd.read_csv('new_train_scaled+som.csv')
train_data_label = pd.read_csv('new_train_label_scaled+som.csv')

In [24]:
train_data

gender  car  reality  income_total  income_type  edu_type  family_type  \
0         0.0  1.0      1.0      0.495528         0.00      0.00         0.00   
1         0.0  0.0      0.0      0.433722         0.25      0.25         0.00   
2         1.0  1.0      0.0      0.395811         0.25      0.00         0.00   
3         0.0  1.0      0.0      0.350973         0.25      0.00         0.00   
4         1.0  1.0      1.0      0.521439         0.25      0.00         0.00   
...       ...  ...      ...           ...          ...       ...          ...   
13223     0.0  0.0      0.0      0.521439         0.25      0.00         0.75   
13224     0.0  1.0      1.0      0.585963         0.50      0.25         0.00   
13225     0.0  0.0      1.0      0.395811         0.25      0.00         1.00   
13226     1.0  0.0      1.0      0.433722         0.50      0.00         0.00   
13227     0.0  1.0      1.0      0.225345         0.25      0.25         0.00   

       house_type  DAYS_BIRTH  DAYS_EMPLOYED  work_phone  email  occyp_type  \
0             0.0    0.649166       0.000000         0.0    0.0    0.000000   
1             0.0    0.462429       0.593706         0.0    0.0    0.055556   
2             0.0    0.331174       0.776724         1.0    0.0    0.111111   
3             0.0    0.261650       0.519263         0.0    0.0    0.166667   
4             0.0    0.485470       0.804310         0.0    0.0    0.222222   
...           ...         ...            ...         ...    ...         ...   
13223         0.0    0.742363       0.893915         0.0    0.0    0.444444   
13224         0.0    0.613515       0.844069         0.0    0.0    0.055556   
13225         0.0    0.396630       0.927880         0.0    1.0    0.000000   
13226         0.0    0.170287       0.802328         0.0    1.0    0.111111   
13227         0.0    0.241875       0.764974         0.0    0.0    0.000000   

       family_size  begin_month        ID  
0         0.071429     0.883333  0.000000  
1         0.142857     0.433333  0.000154  
2         0.071429     0.150000  0.000308  
3         0.214286     0.200000  0.000463  
4         0.142857     0.050000  0.000617  
...            ...          ...       ...  
13223     0.000000     0.716667  0.738514  
13224     0.071429     0.883333  0.287080  
13225     0.071429     0.566667  0.999846  
13226     0.142857     0.266667  0.204903  
13227     0.214286     0.066667  1.000000  

[13228 rows x 16 columns]

In [175]:
test_data

gender  car  reality  income_total  income_type  edu_type  family_type  \
0           1    0        1      0.506222         0.25      0.00         0.25   
1           0    0        1      0.433722         0.00      0.00         0.75   
2           0    0        1      0.125628         0.50      0.00         0.00   
3           1    0        1      0.566278         0.25      0.00         0.25   
4           0    0        1      0.495528         0.25      0.00         0.00   
...       ...  ...      ...           ...          ...       ...          ...   
13223       0    0        1      0.270183         0.00      0.00         0.50   
13224       0    0        1      0.495528         0.25      0.00         0.00   
13225       1    0        1      0.419251         0.50      0.25         0.25   
13226       1    0        1      0.566278         0.50      0.00         0.00   
13227       1    0        1      0.665995         0.25      0.25         0.00   

       house_type  DAYS_BIRTH  DAYS_EMPLOYED  work_phone  email  occyp_type  \
0             0.0    0.134868       0.725219           1      0    0.277778   
1             0.0    0.954068       0.000000           0      0    0.000000   
2             0.0    0.459379       0.749256           1      0    0.055556   
3             0.0    0.217144       0.859203           0      0    0.111111   
4             0.0    0.471149       0.824677           0      0    0.111111   
...           ...         ...            ...         ...    ...         ...   
13223         0.0    0.884997       0.000000           0      0    0.000000   
13224         0.0    0.265488       0.789885           0      0    0.111111   
13225         0.0    0.095252       0.789481           0      1    0.333333   
13226         0.0    0.411839       0.890159           0      1    0.222222   
13227         0.0    0.468393       0.877174           1      0    0.111111   

       family_size  begin_month        ID  cluster  
0         0.000000     0.166667  0.051333    0.500  
1         0.000000     0.866667  0.269616    0.250  
2         0.052632     0.250000  0.688146    0.125  
3         0.105263     0.400000  0.053800    0.500  
4         0.052632     0.900000  0.000000    0.000  
...            ...          ...       ...      ...  
13223     0.000000     0.516667  0.000000    0.250  
13224     0.052632     0.500000  0.420533    0.000  
13225     0.000000     0.400000  0.258055    0.500  
13226     0.052632     0.433333  0.000000    0.500  
13227     0.052632     0.500000  0.053646    0.500  

[13228 rows x 17 columns]

In [25]:
# 기본
X_train = np.array(pd.DataFrame(train_data, columns=[	'gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID']))
y_train = np.array(pd.DataFrame(train_data_label, columns=['credit']))



X_test = np.array(pd.DataFrame(test_data, columns=['gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID']))
y_test = np.array(pd.DataFrame(test_data_label, columns=['credit']))

In [29]:
#  som or kmeans
X_train = np.array(pd.DataFrame(train_data, columns=[	'gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID', 'cluster']))
y_train = np.array(pd.DataFrame(train_data_label, columns=['credit']))



X_test = np.array(pd.DataFrame(test_data, columns=['gender',	'car'	,'reality'	,'income_total'	,'income_type',	'edu_type'	,'family_type'	,'house_type',	'DAYS_BIRTH',
	'DAYS_EMPLOYED',	'work_phone'	,'email'	,'occyp_type',	'family_size'	,'begin_month',	'ID', 'cluster']))
y_test = np.array(pd.DataFrame(test_data_label, columns=['credit']))


In [178]:
X_train

array([[0.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        8.83333333e-01, 0.00000000e+00, 1.25000000e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.33333333e-01, 1.54178230e-04, 3.75000000e-01],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.50000000e-01, 3.08356460e-04, 1.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        5.66666667e-01, 9.99845822e-01, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        2.66666667e-01, 2.04902868e-01, 5.00000000e-01],
       [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        6.66666667e-02, 1.00000000e+00, 1.25000000e-01]])

In [30]:
n_fold = 5
seed = 42
cv = KFold(n_splits=n_fold, shuffle=True, random_state=seed)

In [31]:
model = LogisticRegression(class_weight='balanced')
data = pd.DataFrame(X_train)
data['label'] = y_train
label = pd.DataFrame(data['label'])
features = data.iloc[:,:-1]
n_iter = 0
score_list = []

for train_idx, test_idx in cv.split(X_train):
  n_iter += 1
  print(f'--------------------{n_iter}번째 KFold-------------------')

  print(f'학습 값 : {len(train_idx)} / 검증값 : {len(test_idx)}')
  print('학습 레이블 데이터 분포: \n', train_idx)
  print('검증 레이블 데이터 분포: \n', test_idx)

  label_train = label.iloc[train_idx]
  label_test = label.iloc[test_idx]

  X_train_1, X_test_1 = features.iloc[train_idx, :], features.iloc[test_idx, :]
  y_train_1, y_test_1 = label.iloc[train_idx,:], label.iloc[test_idx,:]

  model.fit(X_train_1, y_train_1)
  preds = model.predict(X_test_1)
  score = f1_score(y_test_1, preds)
 

  print(f'{n_iter}번째 단일 f1_score:{score}')
 
  
  score_list.append(score)

print('==========================================================')
print(f'최종평균 f1_score: {sum(score_list)/len(score_list)}')
  


--------------------1번째 KFold-------------------
학습 값 : 10582 / 검증값 : 2646
학습 레이블 데이터 분포: 
 [    1     2     3 ... 13224 13225 13227]
검증 레이블 데이터 분포: 
 [    0     8    14 ... 13221 13223 13226]
1번째 단일 f1_score:0.6475252939567953
--------------------2번째 KFold-------------------
학습 값 : 10582 / 검증값 : 2646
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13223 13225 13226]
검증 레이블 데이터 분포: 
 [    3    10    12 ... 13219 13224 13227]


/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


2번째 단일 f1_score:0.6357836338418862
--------------------3번째 KFold-------------------
학습 값 : 10582 / 검증값 : 2646
학습 레이블 데이터 분포: 
 [    0     1     2 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [   15    26    27 ... 13207 13216 13222]
3번째 단일 f1_score:0.6611126041386723
--------------------4번째 KFold-------------------
학습 값 : 10583 / 검증값 : 2645
학습 레이블 데이터 분포: 
 [    0     1     3 ... 13225 13226 13227]
검증 레이블 데이터 분포: 
 [    2     6     7 ... 13217 13218 13220]


/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


4번째 단일 f1_score:0.6453744493392071
--------------------5번째 KFold-------------------
학습 값 : 10583 / 검증값 : 2645
학습 레이블 데이터 분포: 
 [    0     2     3 ... 13224 13226 13227]
검증 레이블 데이터 분포: 
 [    1     4     5 ... 13211 13214 13225]
5번째 단일 f1_score:0.6645230439442658
최종평균 f1_score: 0.6508638050441654


/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [183]:
lr = LogisticRegression(class_weight='balanced')
lr.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(class_weight='balanced')

In [184]:
X_train

array([[0.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        8.83333333e-01, 0.00000000e+00, 1.25000000e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.33333333e-01, 1.54178230e-04, 3.75000000e-01],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.50000000e-01, 3.08356460e-04, 1.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        5.66666667e-01, 9.99845822e-01, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        2.66666667e-01, 2.04902868e-01, 5.00000000e-01],
       [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        6.66666667e-02, 1.00000000e+00, 1.25000000e-01]])

In [185]:
y_train

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [186]:
X_test

array([[1.        , 0.        , 1.        , ..., 0.16666667, 0.05133344,
        0.5       ],
       [0.        , 0.        , 1.        , ..., 0.86666667, 0.26961616,
        0.25      ],
       [0.        , 0.        , 1.        , ..., 0.25      , 0.68814552,
        0.125     ],
       ...,
       [1.        , 0.        , 1.        , ..., 0.4       , 0.25805457,
        0.5       ],
       [1.        , 0.        , 1.        , ..., 0.43333333, 0.        ,
        0.5       ],
       [1.        , 0.        , 1.        , ..., 0.5       , 0.05364575,
        0.5       ]])

In [187]:
Y_pred = lr.predict(X_test)

In [188]:
Y_pred.shape

(13228,)

In [189]:
print(len(Y_pred))
Y_pred
for i in Y_pred:
  print(i)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
1
0
1
1
1
0
0
1
0
1
0
1
0
0
0
0
0
0
1
1
0
0
1
1
1
0
0
0
1
1
0
0
1
0
1
0
0
1
1
0
1
1
0
0
0
1
1
0
0
0
1
0
1
1
0
1
1
1
0
1
1
0
0
1
0
0
1
0
0
1
0
0
0
0
1
1
0
1
0
0
1
0
1
1
0
1
0
1
1
1
0
0
1
0
1
0
0
1
0
1
1
0
0
0
1
0
0
1
0
0
0
1
1
0
0
0
0
0
1
0
1
1
0
0
0
0
1
0
0
1
0
0
0
1
0
1
0
1
0
0
1
1
0
1
1
1
0
1
1
1
1
1
1
0
1
0
1
0
0
0
1
1
1
1
1
0
0
1
0
1
0
1
1
0
1
1
1
1
1
0
1
1
0
0
0
1
0
0
0
0
0
1
1
0
1
0
1
0
0
1
0
0
0
0
1
0
1
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
1
0
1
0
1
1
0
1
1
1
1
1
0
0
0
0
1
0
0
1
1
1
1
1
1
0
1
0
0
0
1
1
1
1
1
0
0
0
0
1
1
1
1
1
1
0
0
1
0
1
1
1
0
0
0
1
0
1
0
1
1
1
0
1
1
1
1
0
0
1
1
0
1
0
1
0
0
1
1
1
0
0
0
0
1
0
0
0
0
1
0
0
1
1
0
1
0
0
0
0
0
0
1
0
0
1
1
1
1
0
0
1
0
1
0
0
0
0
1
1
0
1
0
1
1
1
1
0
1
0
0
0
1
1
1
0
1
1
1
1
0
1
0
0
1
1
0
1
0
1
0
1
1
1
0
0
0
1
0
1
0
0
0
1
0
0
1
0
1
0
0
0
0
0
0
0
1
1
1
0
0
1
0
1
1
0
1
1
0
0
0
0
1
1
1
1
0
0
1
1
1
1
1
0
1
0
1
1
1
1
1
1
1
0
0
1
1
0
1
1
1
0
1
0
0
1
0
0
0
0
1
1
1
1
0
0
1
1
1
1
0
0
1
1
1
1
1
0
0
1
1
0
0
0
0
0
1
1
0


In [190]:
np.savetxt('val.txt', y_pred, fmt='%d', delimiter=',')